delicious/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('food.urls', namespace="food")),
    url(r'^admin/', include(admin.site.urls)),
]

food/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^tweet/(?P<pk>[0-9]+)/$', views.TweetDetailView.as_view(), name='tweet_detail'),
    url(r'^tweet/(?P<tweet_id>[0-9]+)/buy/$', views.tweet_buy, name='tweet_buy'),
    url(r'^tweet/(?P<pk>[0-9]+)/discuss/$', views.DiscussView.as_view(), name='discuss'),
    url(r'^discuss/add/$', views.discuss_add, name='discuss_add'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^cart/buy/$', views.cart_buy, name='cart_buy'),
    url(r'^cart/buy/paid/$', views.cart_paid, name='cart_paid'),
    url(r'^order/(?P<pk>[0-9]+)/increase$', views.order_increase, name='order_increase'),
    url(r'^order/(?P<pk>[0-9]+)/decrease$', views.order_decrease, name='order_decrease'),
    url(r'^found/$', views.found, name='found'),
    url(r'^forward/$', views.forward, name='forward'),
]

food/models.py
# -*- coding: utf-8 -*-
"""
python manage.py makemigrations
python manage.py migrate
"""
from django.db import models


class User(models.Model):
    name = models.CharField(max_length=200)
    photo = models.CharField(max_length=200)

    def __unicode__(self):
        return self.name


class Tweet(models.Model):
    author = models.ForeignKey(User)

    type = models.CharField(max_length=200)  # 原创或转发
    publish_date = models.DateTimeField('发布时间')
    title = models.CharField(max_length=200)
    logo = models.CharField(max_length=200)
    content = models.TextField()
    vote = models.IntegerField("赞", default=0)
    # 菜谱专有字段
    visit = models.IntegerField(default=0)
    score = models.FloatField("评分", default=0)
    # 转发专有字段
    original_id = models.BigIntegerField("菜谱ID", default=0)

    def __unicode__(self):
        return self.title


class Comment(models.Model):
    author = models.ForeignKey(User)
    tweet = models.ForeignKey(Tweet)

    content = models.CharField(max_length=300)

    def __unicode__(self):
        return self.content


class Ingredient(models.Model):
    tweet = models.ForeignKey(Tweet)

    name = models.CharField(max_length=200)  # 食材名称
    number = models.IntegerField(default=0)  # 数量
    unit = models.CharField(max_length=200)  # 单位

    def __unicode__(self):
        return ' - '.join([self.tweet.title, self.name])


class Procedure(models.Model):
    tweet = models.ForeignKey(Tweet)

    step = models.IntegerField(default=0)
    picture = models.CharField(blank=True, max_length=200)
    content = models.CharField(max_length=500)

    def __unicode__(self):
        return ' - '.join([self.tweet.title, str(self.step)])


class Supplier(models.Model):
    name = models.CharField(max_length=200)
    link = models.CharField(max_length=200)

    def __unicode__(self):
        return self.name


class Price(models.Model):
    tweet = models.ForeignKey(Tweet)
    supplier = models.ForeignKey(Supplier)

    value = models.IntegerField(default=0)

    def __unicode__(self):
        return '%s: %s, %s' % (self.tweet.title, self.supplier.name, str(self.value) + u'元')


class Order(models.Model):
    user = models.ForeignKey(User)
    price = models.ForeignKey(Price)
    number = models.IntegerField(default=0)
    has_paid = models.BooleanField(default=False)

    def __unicode__(self):
        return ', '.join([self.user.name, self.price.tweet.title, str(self.number) + u'个'])

food/views.py
# -*- coding: utf-8 -*-
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views import generic
from .models import *


class IndexView(generic.ListView):
    template_name = 'food/index.html'
    context_object_name = 'tweets'

    def get_queryset(self):
        return Tweet.objects.order_by('-publish_date')


def found(request):
    return render(request, 'food/found.html')


def forward(request):
    return render(request, 'food/forward.html')


class TweetDetailView(generic.DetailView):
    model = Tweet
    template_name = 'food/tweet.html'


class DiscussView(generic.DetailView):
    model = Tweet
    template_name = 'food/discuss.html'


def tweet_buy(request, tweet_id):
    user_id = int(request.POST['user'])
    price_ud = int(request.POST['price'])
    number = int(request.POST['number'])

    order = Order.objects.filter(user=User.objects.get(pk=user_id), price=Price.objects.get(pk=price_ud),
                                 has_paid=False).all()
    if order:
        order = order[0]
        order.number += number
    else:
        order = Order(user=User.objects.get(pk=user_id), price=Price.objects.get(pk=price_ud), number=number)
    order.save()
    return HttpResponseRedirect(reverse('food:cart'))


def discuss_add(request):
    user_id = int(request.POST['user_id'])
    tweet_id = int(request.POST['tweet_id'])
    content = request.POST['content']

    comment = Comment(author=User.objects.get(pk=user_id), tweet=Tweet.objects.get(pk=tweet_id), content=content)
    comment.save()

    return HttpResponseRedirect(reverse('food:discuss', args=(tweet_id,)))


def cart(request):
    orders = Order.objects.filter(has_paid=False).all()
    total = sum([o.number * o.price.value for o in orders])
    user = orders[0].user if orders else ''

    context = {'user': user, 'orders': orders, 'total': total}
    return render(request, 'food/cart.html', context)


def cart_paid(request):
    return render(request, 'food/paid.html')


def cart_buy(request):
    user_id = int(request.POST['user'])

    orders = Order.objects.filter(user=User.objects.get(pk=user_id)).all()
    for o in orders:
        o.has_paid = True
        o.save()

    return HttpResponseRedirect(reverse('food:cart_paid'))


def order_increase(request, pk):
    order = Order.objects.get(pk=pk)
    order.number += 1
    order.save()
    return HttpResponseRedirect(reverse('food:cart'))


def order_decrease(request, pk):
    order = Order.objects.get(pk=pk)
    if order.number == 1:
        order.delete()
    else:
        order.number -= 1
        order.save()
    return HttpResponseRedirect(reverse('food:cart'))

food/templates/food/base.html
{% load staticfiles %}
<html>
<head>
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="{% static 'food/materialize/css/materialize.min.css' %}"
          media="screen,projection"/>

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
</head>

<body>
<!--Import jQuery before materialize.js-->
<script type="text/javascript" src="{% static 'food/js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'food/materialize/js/materialize.min.js' %}"></script>
<div class="navbar-fixed">
    <nav>
        <div class="nav-wrapper">
            <a href="#!" class="brand-logo">{% block header_name%}美食易{% endblock%}</a>
            <ul class="right">
                <li><a href="{% url 'food:cart' %}"><i class="mdi-action-shopping-cart"></i></a></li>
            </ul>
        </div>
    </nav>
</div>
{% block page_content%}{% endblock%}
<div class="row">
      <div class="col s12">&nbsp;</div>
</div>
<div class="navbar-fixed" style="position: absolute;bottom: 0;">
    <nav>
        <div class="nav-wrapper">
            <ul class="center">
                <li><a href="{% url 'food:index' %}"><i class="mdi-action-home"></i></a></li>
                <li><a href="{% url 'food:found' %}"><i class="mdi-action-search"></i></a></li>
                <li><a href="#"><i class="mdi-social-person"></i></a></li>
                <li><a href="#"><i class="mdi-content-add-circle"></i></a></li>
            </ul>
        </div>
    </nav>
</div>
</body>
</html>

food/templates/food/cart.html
{% extends "food/base.html" %}
{% load staticfiles %}
{% block header_name %}购物车{% endblock %}
{% block page_content %}
<div class="row">
    <table>
        <thead>
        <tr>
            <th data-field="food">您选购的菜</th>
            <th data-field="unit_price">单价</th>
            <th data-field="store">店铺</th>
            <th data-field="number">数量</th>
        </tr>
        </thead>

        <tbody>
        {% for order in orders %}
        <tr>
            <td>{{ order.price.tweet.title }}</td>
            <td>￥{{ order.price.value }}</td>
            <td>{{ order.price.supplier.name }}</td>
            <td>
            <th><a class="btn-floating btn-small waves-effect waves-light blue-grey"
                   href="{% url 'food:order_decrease' order.id %}"><i
                    class="mdi-content-remove"></i></a></th>
            <th><input value="{{ order.number }}" id="number" type="text" class="validate" length="2"/></th>
            <th><a class="btn-floating btn-small waves-effect waves-light green"
                   href="{% url 'food:order_increase' order.id %}"><i class="mdi-content-add"></i></a>
            </th>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<div class="row">
    总价: {{ total }}
</div>
<div class="row">
    <form class="col s12" action="{% url 'food:cart_buy' %}" method="post">
        <input type="hidden" name="user" value="{{ user.id }}"/>
        {% csrf_token %}

        <div class="row">
            <div class="input-field col s6">
                <input placeholder="" id="customer_name" type="text" class="validate" value="张三">
                <label for="customer_name">收货人姓名</label>
            </div>
            <div class="input-field col s6">
                <input id="phone_number" type="text" class="validate" length="11" value="13579246810">
                <label for="phone_number">手机号</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
                <input id="address" type="text" class="validate" value="北京">
                <label for="address">地址</label>
            </div>
        </div>
        <div class="row">
            <label>期望收货时间</label>
            <input id="ship_datepicker" type="date" class="datepicker" value="2015/04/18">
        </div>
        <div class="row">
            <div class="col s3">&nbsp;</div>
            <div class="col s6">
                <button class="btn waves-effect waves-light" type="submit" name="action">确认并支付
                    <i class="mdi-content-send right"></i>
                </button>
            </div>
            <div class="col s3">&nbsp;</div>
        </div>
    </form>
</div>
{% endblock %}

food/templates/food/discuss.html
{% extends "food/base.html" %}
{% load staticfiles %}
{% block header_name %}评论{% endblock %}
{% block page_content %}
{% for comment in tweet.comment_set.all %}
<div class="col s12 m8 offset-m2 l6 offset-l3">
    <div class="card-panel grey lighten-5 z-depth-1">
        <div class="row valign-wrapper">
            <div class="col s2">
                <img src="{% static 'food/images/user_avatar/' %}{{ comment.author.photo }}" alt=""
                     class="circle responsive-img">
                <!-- notice the "circle" class -->
            </div>
            <div class="col s10">
              <span class="black-text">
                {{ comment.content }}
              </span>
            </div>
        </div>
    </div>
</div>
{% endfor %}
<br/><br/><br/><br/>


<div class="row">
    <form action="{% url 'food:discuss_add'%}" method="post">
        {% csrf_token %}
        <input type="hidden" name="tweet_id" value="{{ tweet.id }}"/>
        <input type="hidden" name="user_id" value="3"/>

        <div class="input-field col s6">
            <input name="content" id="content" type="text" class="validate">
            <label class="active" for="content">输入你的评论信息<i class="mdi-file-cloud left"></i></label>

        </div>
        <div class="col s6">
            <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                <i class="mdi-content-send right"></i>
            </button>
        </div>
    </form>
</div>
<br/>
<br/>

{% endblock %}

food/templates/food/forward.html
<!doctype html>
{% load staticfiles %}
<html class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>黑客马拉松－kitchen</title>

    <!-- Set render engine for 360 browser -->
    <meta name="renderer" content="webkit">

    <!-- No Baidu Siteapp-->
    <meta http-equiv="Cache-Control" content="no-siteapp"/>

    <link type="text/css" rel="stylesheet" href="{% static 'food/materialize/css/materialize.min.css' %}"
          media="screen,projection"/>
    <script type="text/javascript" src="{% static 'food/js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'food/materialize/js/materialize.min.js' %}"></script>

    <link rel="icon" type="image/png" href="{% static 'food/images/favicon.png' %}">

    <!-- Add to homescreen for Chrome on Android -->
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" sizes="192x192" href="{% static 'food/images/app-icon72x72@2x.png' %}">

    <!-- Add to homescreen for Safari on iOS -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="Amaze UI"/>
    <link rel="apple-touch-icon-precomposed" href="{% static 'food/images/app-icon72x72@2x.png' %}">

    <!-- Tile icon for Win8 (144x144 + tile color) -->
    <meta name="msapplication-TileImage" content="{% static 'food/images/app-icon72x72@2x.png' %}">
    <meta name="msapplication-TileColor" content="#0e90d2">

    <link rel="stylesheet" href="{% static 'food/css/amazeui.min.css' %}">
    <link rel="stylesheet" href="{% static 'food/css/app.css' %}">
</head>
<body>
<div class="forward">
    <div class="header">
        <ul>
            <li class="list1"><a href="{% url 'food:index' %}">返回</a></li>
            <li class="list2">晒作品</li>
            <li class="list3">● ● ●</li>
        </ul>
    </div>
    <div class="card">
        <img src="{% static 'food/images/dishes/' %}{{tweet.logo}}">

        <p>{{ tweet.title }}</p>

        <div class="info">
            <p>{{ tweet.content }}</p>
        </div>
    </div>
    <p>做法</p>
</div>

</body>
</html>

food/templates/food/found.html
{% extends "food/base.html" %}
{% load staticfiles %}
{% block header_name %}发现{% endblock %}
{% block page_content %}
<div>
    <div class="row">
        <div class="col s12">
            <ul class="tabs">
                <li class="tab col s4"><a href="#test1">本季推荐</a></li>
                <li class="tab col s4"><a class="active" href="#test2">本周评论最多</a></li>
                <li class="tab col s4"><a href="#test3">本周购买最多</a></li>
            </ul>
        </div>
        <div id="test1" class="col s12">本季推荐菜谱</div>
        <div id="test2" class="col s12">本周评论最多菜谱</div>
        <div id="test3" class="col s12">本周购买最多的菜谱</div>
    </div>
</div>
{% endblock %}

food/templates/food/index.html
{% extends "food/base.html" %}
{% load staticfiles %}
{% block page_content %}
<div>
    {% for tweet in tweets %}
    <div class="card medium">
        <div class="card-image waves-effect waves-block waves-light">
            <img class="activator" src="{% static 'food/images/dishes/' %}{{tweet.logo}}">
        </div>
        <div class="card-content">
            <span class="card-title activator grey-text text-darken-4">
                <a href="{% url 'food:tweet_detail' tweet.id %}">{{ tweet.title }}</a>
                <i class="mdi-navigation-more-vert right"></i></span>
            <ul>
                <a class="btn-floating btn-medium waves-effect waves-light red"
                   href="{% url 'food:discuss' tweet.id %}">
                    <i class="tiny mdi-editor-mode-comment"></i></a>
                <a class="btn-floating btn-medium waves-effect waves-light red"><i class="tiny mdi-action-thumb-up"></i></a>
            </ul>
        </div>
        <div class="card-reveal">
            <span class="card-title grey-text text-darken-4">{{ tweet.title }}
                <i class="mdi-navigation-close right"></i>
            </span>

            <p>{{ tweet.content }}</p>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

food/templates/food/paid.html
{% extends "food/base.html" %}
{% load staticfiles %}
{% block page_content %}
        <br/><br/><br/>
<p align="center">购买成功</p>
<br/><br/><br/><br/><br/><br/><br/>
{% endblock %}

food/templates/food/tweet.html
<!doctype html>
{% load staticfiles %}
<html class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>黑客马拉松－kitchen</title>

    <!-- Set render engine for 360 browser -->
    <meta name="renderer" content="webkit">

    <!-- No Baidu Siteapp-->
    <meta http-equiv="Cache-Control" content="no-siteapp"/>

    <link type="text/css" rel="stylesheet" href="{% static 'food/materialize/css/materialize.min.css' %}"
          media="screen,projection"/>
    <script type="text/javascript" src="{% static 'food/js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'food/materialize/js/materialize.min.js' %}"></script>

    <link rel="icon" type="image/png" href="{% static 'food/images/favicon.png' %}">

    <!-- Add to homescreen for Chrome on Android -->
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" sizes="192x192" href="{% static 'food/images/app-icon72x72@2x.png' %}">

    <!-- Add to homescreen for Safari on iOS -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="Amaze UI"/>
    <link rel="apple-touch-icon-precomposed" href="{% static 'food/images/app-icon72x72@2x.png' %}">

    <!-- Tile icon for Win8 (144x144 + tile color) -->
    <meta name="msapplication-TileImage" content="{% static 'food/images/app-icon72x72@2x.png' %}">
    <meta name="msapplication-TileColor" content="#0e90d2">

    <link rel="stylesheet" href="{% static 'food/css/amazeui.min.css' %}">
    <link rel="stylesheet" href="{% static 'food/css/app.css' %}">
</head>
<body>
<div class="menu">
    <div class="header">
        <ul>
            <li class="list1"><a href="{% url 'food:index' %}">返回</a></li>
            <li class="list2">菜谱正文</li>
            <li class="list3">● ● ●</li>
        </ul>
    </div>
    <div class="card">
        <img src="{% static 'food/images/dishes/' %}{{tweet.logo}}">

        <p>{{ tweet.title }}</p>

        <div class="info">
            <p>{{ tweet.content }}</p>
        </div>
    </div>

    <div class="material">
        <p>用料</p>
    </div>

    <table>
        <tbody>
        {% for ingredient in tweet.ingredient_set.all %}
        <tr>
            <td class="left">{{ ingredient.name }}</td>
            <td class="right">{{ ingredient.number }} {{ ingredient.unit }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

    <div class="process">
        <p>做法</p>

        {% for step in tweet.procedure_set.all %}
        <div class="step">
            {% if step.picture %}
            <img src="{% static 'food/images/dishes/' %}{{ step.picture }}">
            {% endif %}
            <p>{{ step.step }} - {{ step.content }}</p>
        </div>
        {% endfor %}
    </div>

    <div class="forward-head">
        <p>买家秀</p>
    </div>
    <div class="bottom">
        <ul>
            <li><img src="{% static 'food/images/dishes/716ff7f2d76211e49ac7b8ca3aeed2d7.jpg' %}"></li>
            <li><img src="{% static 'food/images/dishes/7b4006a0e3f111e4b77cb8ca3aeed2d7.jpg' %}"></li>
            <li><img src="{% static 'food/images/dishes/1bcbe9b8c3bd11e4a770b8ca3aeed2d7.jpg' %}"></li>
        </ul>
    </div>

    <p>推荐供应商</p>

    <form action="{% url 'food:tweet_buy' tweet.id %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="user" value="3"/>
        {% for price in tweet.price_set.all %}
        <p>
            <input name="price" value="{{ price.id }}" type="radio" id="price{{ price.id }}" checked="true"/>
            <label for="price{{ price.id }}">{{ price.supplier.name }}, {{ price.value }}元</label>
        </p>
        {% endfor %}

        <p>购买数量: <input type="text" name="number" value="1"/></p>

        <p><input type="submit" value="加入购物车"/></p>

    </form>

</div>

</body>
</html>